development:
  adapter: mysql2
  encoding: utf8
  database: tasksboard_development
  pool: 5
  username: root
  password: LoadMe5010!!!
test:
  adapter: mysql2
  encoding: utf8
  database: tasksboard_test
  pool: 5
  username: root
  password: LoadMe5010!!!
production:
  adapter: mysql2
  encoding: utf8
  database: tasksboard_production
  pool: 5
  username: root
  password: LoadMe5010!!!
